version: "3.9"

services:
  server:
    build: .
    image: pulsey-game-server:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pulsey
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pulsey
    depends_on:
      - mongo

volumes:
  mongodb:
