version: "3.9"

services:
#  server:
#    build: .
#    image: pulsey-game-server:latest
#    ports:
#      - "3000:3000"
#    environment:
#      DOCKER_ENVIRONMENT: 1
#    depends_on:
#      - mongo

  mongo:
    image: mongo:4.4-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - mongo

volumes:
  mongodb:
