AppVersion: 1.0.0

Server:
  Port: 3000
  Development: true
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  MaxConnectionIdle: 5
  MaxConnectionAge: 5

MongoDB:
  URI: "mongodb://mongo:27017"
  User: "admin"
  Password: "admin"
  DB: "pulsey-db"
